-- 1. Create tables

-- Drop tables if they exist (clean setup)
DROP TABLE IF EXISTS historial_decisiones;
DROP TABLE IF EXISTS solicitudes_reposicion;
DROP TABLE IF EXISTS proveedores;
DROP TABLE IF EXISTS inventario;

-- Table for Inventory
CREATE TABLE inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto VARCHAR(255) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    talla VARCHAR(50) NOT NULL,
    stock_actual INTEGER NOT NULL DEFAULT 0,
    consumo_diario_promedio NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    imagen VARCHAR(1000)
);

-- Table for Suppliers
CREATE TABLE proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES inventario(id) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    costo_unitario NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    plazo_entrega_dias INTEGER NOT NULL DEFAULT 1
);

-- Table for Reposition Requests
CREATE TABLE solicitudes_reposicion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES inventario(id) ON DELETE CASCADE,
    proveedor_id BIGINT REFERENCES proveedores(id) ON DELETE CASCADE,
    cantidad INTEGER NOT NULL DEFAULT 0,
    costo_estimado NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    estado VARCHAR(50) NOT NULL DEFAULT 'pendiente',
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table for Decision History
CREATE TABLE historial_decisiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES inventario(id) ON DELETE CASCADE,
    decision VARCHAR(500) NOT NULL,
    explicacion TEXT NOT NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security (RLS), but add simple policies to allow public reads and writes for the MVP
-- If you prefer security, you can configure authentications, but for the Hackathon MVP, we will make them publicly accessible.

ALTER TABLE inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE solicitudes_reposicion ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_decisiones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON inventario FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON proveedores FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON solicitudes_reposicion FOR SELECT USING (true);
CREATE POLICY "Allow public write" ON solicitudes_reposicion FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read" ON historial_decisiones FOR SELECT USING (true);
CREATE POLICY "Allow public write" ON historial_decisiones FOR INSERT WITH CHECK (true);

-- 2. Insert Mock Data

-- Seed Inventario
INSERT INTO inventario (producto, categoria, talla, stock_actual, consumo_diario_promedio, imagen) VALUES
('Chaqueta Denim Classic', 'Outerwear', 'L', 5, 2.50, 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=700&q=85'),
('Blazer Sastrero Arena', 'Sastrería', 'M', 8, 2.66, 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=700&q=85'),
('Pantalón Cargo Olive', 'Bottoms', '32', 11, 2.20, 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=700&q=85'),
('Camisa Oxford Blanca', 'Camisas', 'M', 35, 1.20, 'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=700&q=85'), -- Healthy product (days remaining: 29)
('Vestido Midi Lino', 'Vestidos', 'S', 2, 0.00, 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=700&q=85'), -- Zero daily consumption case
('Camiseta Básica Algodón', 'Camisetas', 'M', 15, 4.00, 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=700&q=85'),
('Jeans Slim Fit Indigo', 'Jeans', '32', 50, 1.50, 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=700&q=85'),
('Tenis Urban Retro', 'Zapatos', '42', 4, 1.00, 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=700&q=85'),
('Gorra Deportiva Active', 'Gorras', 'Única', 12, 3.00, 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=700&q=85');

-- Seed Proveedores
-- Product 1: Chaqueta Denim Classic (id: 1)
INSERT INTO proveedores (producto_id, nombre, costo_unitario, plazo_entrega_dias) VALUES
(1, 'ModaExpress', 28.50, 4),
(1, 'Confecciones Express', 32.00, 2); -- Alternative supplier (more expensive but faster)

-- Product 2: Blazer Sastrero Arena (id: 2)
INSERT INTO proveedores (producto_id, nombre, costo_unitario, plazo_entrega_dias) VALUES
(2, 'Textil Andino', 45.00, 3);

-- Product 3: Pantalón Cargo Olive (id: 3)
INSERT INTO proveedores (producto_id, nombre, costo_unitario, plazo_entrega_dias) VALUES
(3, 'Distrito 9', 18.00, 5);

-- Product 4: Camisa Oxford Blanca (id: 4)
INSERT INTO proveedores (producto_id, nombre, costo_unitario, plazo_entrega_dias) VALUES
(4, 'Camisas del Norte', 15.00, 6);

-- Product 5: Vestido Midi Lino (id: 5)
INSERT INTO proveedores (producto_id, nombre, costo_unitario, plazo_entrega_dias) VALUES
(5, 'Lino Real', 35.00, 4);

-- Product 6: Camiseta Básica Algodón (id: 6)
INSERT INTO proveedores (producto_id, nombre, costo_unitario, plazo_entrega_dias) VALUES
(6, 'CottonStyle', 8.00, 3);

-- Product 7: Jeans Slim Fit Indigo (id: 7)
INSERT INTO proveedores (producto_id, nombre, costo_unitario, plazo_entrega_dias) VALUES
(7, 'DenimFactory', 22.00, 5);

-- Product 8: Tenis Urban Retro (id: 8)
INSERT INTO proveedores (producto_id, nombre, costo_unitario, plazo_entrega_dias) VALUES
(8, 'Calzado Express', 30.00, 2),
(8, 'Calzado Premium', 35.00, 1);

-- Product 9: Gorra Deportiva Active (id: 9)
INSERT INTO proveedores (producto_id, nombre, costo_unitario, plazo_entrega_dias) VALUES
(9, 'Accesorios Sport', 6.00, 5);

-- Seed some existing Requests & History for initial display
INSERT INTO solicitudes_reposicion (producto_id, proveedor_id, cantidad, costo_estimado, estado) VALUES
(4, 5, 40, 600.00, 'aprobada'),
(3, 4, 25, 450.00, 'en tránsito');

INSERT INTO historial_decisiones (producto_id, decision, explicacion) VALUES
(4, 'Compra de 40 unidades', 'Se aprobó la reposición automática sugerida por el sistema para evitar riesgo en fin de semana.'),
(3, 'Compra de 25 unidades', 'Solicitud pendiente de aprobación para reponer inventario del Pantalón Cargo Olive.');
